import Head from 'next/head'
import { Header } from './Header.jsx'
import Homepage from '../pages/Homepage.jsx'

export default function Home() {
  return (
    <>
      <Head>
        <title>Spectrum</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className="bg-red-400 h-11 w-11 shadow shadow-pink-300"></div> */}

      <Header />
      <Homepage />
    </>
  )
}
